version: '3'
services:
    backup: 
        build:
            context: .
            dockerfile: Dockerfile
        image:  pmorgan3/mongobackupminio:backup
        environment:
            - MINIO_ACCESSKEY=accesskey
            - MINIO_SECRETKEY=secretkey
            - MINIO_ENDPOINT=minio:9000
            - MINIO_BUCKET=TestBucket
            - MONGO_DATABASE=Testdb
            - MONGO_PORT=27017
            - MONGO_HOST=db:27017
            - MONGO_USER
            - MONGO_PASSWORD
            - ZIP_NAME
            - Verbose
            - SSL
        volumes:
            - ./config:/config
        logging:
            driver: awslogs
            options:
                awslogs-group: ecs-development
                awslogs-region: us-east-1
                awslogs-stream-prefix: mongo-backup
