version: '3'
services:
    backup: 
        build:
            context: .
            dockerfile: Dockerfile
        image:  pmorgan3/mongobackupminio:backup
        environment:
            - MINIO_ACCESSKEY=accesskey
            - MINIO_SECRETKEY=secretkey
            - MINIO_ENDPOINT=minio:9000
            - MINIO_BUCKET=testbucket
            - MONGO_DATABASE=Testdb
            - MONGO_PORT=27017
            - MONGO_HOST=db:27017
            - MONGO_USER=mongouser
            - MONGO_PASSWORD=password
            - ZIP_NAME=zip_name.zip
        volumes:
            - ./config:/config
   