version: '3'
services:
    backup-mongodb:
        image: mongo:4.2.2
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongouser
            - MONGO_INITDB_ROOT_PASSWORD=password
        command: --bind_ip_all
        ports:
            - 27017
        logging:
            driver: awslogs
            options:
                awslogs-group: mongobackup
                awslogs-region: us-east-1
                awslogs-stream-prefix: mongodb
    backup-mongodb-ui:
        image: mongo-express
        restart: always
        ports:
            - 8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: password
        depends_on:
            - db
        logging:
            driver: awslogs
            options:
                awslogs-group: mongobackup
                awslogs-region: us-east-1
                awslogs-stream-prefix: mongodb-ui
        version: "3.3"
    traefik:
      image: traefik:v2.2
      container_name: traefik
      command:
        - --log.level=DEBUG
        - --api.insecure=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=true
        - --entrypoints.web.address=:80
      ports:
        - 80:80
        - 8080:8080
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    mongo:
      image: mongodb
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.mongodb.rule=HostSNI(`mongodb.localhost`)
        - traefik.tcp.routers.mongodb.tls.passthrough=true
      ports:
        - 27017
